version: "3"
services:
    nexus:
        container_name: nexus
        image: sonatype/nexus
        restart: always
        ports:
            - 8081:8081
# http://localhost:8081/nexus/service/local/status
# http://localhost:8081/nexus/

# creds: admin:admin123
