version: "3"
services:
    mitmproxy:
        container_name: mitmproxy
        image: mitmproxy/mitmproxy
        restart: always
        command: ['mitmweb', '--web-host', '0.0.0.0']
        ports:
            - 8080:8080
            - 8081:8081
