global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: [ 'host.docker.internal:9090' ]
    - job_name: 'otel-collector'
      static_configs:
          - targets: [ 'host.docker.internal:8888' ]
    - job_name: 'otel-collector-export'
      static_configs:
          - targets: [ 'host.docker.internal:8889' ]
