version: '3'
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management-alpine
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
