version: '3'
services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        restart: always
        volumes:
            - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana
        container_name: grafana
        restart: always
        volumes:
            - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
            - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
        ports:
            - 3000:3000

# Grafana creds: admin:admin
