version: "3"
services:
    graphite:
        container_name: graphite
        image: graphiteapp/graphite-statsd
        restart: always
        environment:
            STATSD_INTERFACE: tcp
        ports:
            - 80:80
            - 2003:2003
            - 2004:2004
            - 2023:2023
            - 2024:2024
            - 8125:8125
            - 8126:8126
# creds: root:root
