version: '3'
services:
  mariadb:
    container_name: mariadb
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./local-data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    environment:
        ADMINER_DEFAULT_SERVER: mariadb
    depends_on:
      - mariadb
    ports:
      - 8888:8080
