version: "3"
services:
    telegraf:
        image: telegraf
        container_name: telegraf
        extra_hosts: ['host.docker.internal:host-gateway']
        restart: always
        volumes:
            - ./config/telegraf.conf:/etc/telegraf/telegraf.conf:ro \
        ports:
            - 8125:8125/udp
